// <auto-generated />
using System;
using Banica_Luis_Proiect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Banica_Luis_Proiect.Migrations
{
    [DbContext(typeof(Banica_Luis_ProiectContext))]
    [Migration("20230113113851_assignedData")]
    partial class assignedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Banica_Luis_Proiect.Models.Automobil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataInchirierii")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.ToTable("Automobil");
                });

            modelBuilder.Entity("Banica_Luis_Proiect.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NumeCategorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("Banica_Luis_Proiect.Models.CategorieAutomobil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AutomobilId")
                        .HasColumnType("int");

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutomobilId");

                    b.HasIndex("CategorieId");

                    b.ToTable("CategorieAutomobil");
                });

            modelBuilder.Entity("Banica_Luis_Proiect.Models.CategorieAutomobil", b =>
                {
                    b.HasOne("Banica_Luis_Proiect.Models.Automobil", "Automobil")
                        .WithMany("CategoriiAutomobil")
                        .HasForeignKey("AutomobilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Banica_Luis_Proiect.Models.Categorie", "Categorie")
                        .WithMany("CategoriiAutomobil")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Automobil");

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Banica_Luis_Proiect.Models.Automobil", b =>
                {
                    b.Navigation("CategoriiAutomobil");
                });

            modelBuilder.Entity("Banica_Luis_Proiect.Models.Categorie", b =>
                {
                    b.Navigation("CategoriiAutomobil");
                });
#pragma warning restore 612, 618
        }
    }
}
